extends('layouts.admin');
@section('content')
<table>
    <thead>
    <tr>
        <th>ID</th>
        <th>Title</th>
        <th>CreatedAt</th>
        <th></th>
    </tr>
    </thead>
</table>
@endsection